### ISSUE TITLE
more like news issue

### ISSUE THREAD

**Issue by panchipanchi** [cisko99za/cisko99za#1]
you want to download spotify playlists?
check out: http://tiny.cc/bobpizza

**Comment by cisko99za** [comment]
tanxs for your suggestion. but run music.exe i have error, see at: https://pasteboard.co/ID7pfry.jpg
error loading program
file "music.py" line 17 in <module>
name error name z is not defined
failed to excute script music

**Comment by panchipanchi** [comment]
i tried it....it works, just try running it again until it works, i use a free server to
authenticate the app, sometimes the server doesn't respond...., i've been doing
major tests on my new forum site http://tiny.cc/askit which shares the same server, but when the
traffic is low, it responds better, just run again. no ones really using either app or site... lol but yesterday the amazon and google bots decided to crawl my website at same time.. i had like over 100 requests...lol.. .i guess i should create a fix by having he program try authenticating on an endless loop, so eventually it will work.... i authenticate the app for a few reasons, one being i would probably like to charge a license fee sometime later, but for now its all free, also so it makes sure the app you're running is the one I created, and not edited by someone else, ie: injected with viruses..etc..

**Comment by panchipanchi** [comment]
i mean a free server, the server is fine

**Comment by cisko99za** [comment]
i have try and try and try and try..... today, yesterday..... same same error....
and cmd stopping! and at yuor forum tiny.cc/askit i have try to comment or add answer but it is not possible.... i have also try to register but on all field compiled the new page respond:
"compile all field" !....
this i very frustating... your prog don't work (for me), forum is not accessible..... oh my god...!

**Comment by panchipanchi** [comment]
ok take it easy, sorry you're having issues... i changed a authen value
temporarily, so it may work better now, if not its a unicode issue, which i
have to look into, the website had a bug on register mode 2 days ago... it
is fixed, but u dont need that to register, if u want to help me out on
chasing this error, you can post the content of whatever post you're trying
to submit, it could also be a unicode thing, my advise is try a short post
with just text first, but its working for me on chrome browser and firefox
mobile

>

**Comment by panchipanchi** [comment]
i made some updates, register should work, u dont need to register to post or make comments
music.exe authenticates everyone now... it does need internet access and permission to write files in root directory, for some windows computers that means click yes allow internet or not firewall and/or run as admin (right click), if u want to try again, delete music.exe, ffmpeg.exe, redownload music.exe, right click run as admin

**Comment by cisko99za** [comment]
ohhh yesss! now work correctly! tanxs so much for your attention! byeeeeee

**Comment by panchipanchi** [comment]
http://bobpizza2.pythonanywhere.com/ask?topic=47

**Comment by cisko99za** [comment]
i can not reply form my mail, only receive. anyway i try post my comment at your blog but not work...
i write, click on comment, page it recharges and stop... no message add on your blog and page is freezed....!

**Comment by panchipanchi** [comment]
i made an edit, you may have to take out cookie or try in incognito mode.
Is english your first language? Im going to make anfew translations to the
website, but for now you cannpost in any language
